# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSplitter', '0006_bill_split_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
